spring:
  application:
    name: hub-service
  datasource:
    url: jdbc:mysql://localhost:3306/hub-service
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root0703}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/