spring:
  application:
    name: hub-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    auditing:
      auditor-aware-strategy: org.springframework.data.domain.AuditorAware
      auditor-impl: com.example.CustomAuditorAware  # 구현 클래스 지정
server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/